export const CLEAR_ORGANIZATION = 'CLEAR_ORGANIZATION';

export const GET_ORGANIZATION = 'GET_ORGANIZATION';
export const GET_ORGANIZATION_PENDING = 'GET_ORGANIZATION_PENDING';
export const GET_ORGANIZATION_FULFILLED = 'GET_ORGANIZATION_FULFILLED';
export const GET_ORGANIZATION_REJECTED = 'GET_ORGANIZATION_REJECTED';

export const IS_ORGANIZATION_ADMIN_EXIST = 'IS_ORGANIZATION_ADMIN_EXIST';
export const IS_ORGANIZATION_ADMIN_EXIST_PENDING = 'IS_ORGANIZATION_ADMIN_EXIST_PENDING';
export const IS_ORGANIZATION_ADMIN_EXIST_FULFILLED = 'IS_ORGANIZATION_ADMIN_EXIST_FULFILLED';
export const IS_ORGANIZATION_ADMIN_EXIST_REJECTED = 'IS_ORGANIZATION_ADMIN_EXIST_REJECTED';


