export const CLEAR_REQUEST = 'CLEAR_REQUEST';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const CREATE_REQUEST_PENDING = 'CREATE_REQUEST_PENDING';
export const CREATE_REQUEST_FULFILLED = 'CREATE_REQUEST_FULFILLED';
export const CREATE_REQUEST_REJECTED = 'CREATE_REQUEST_REJECTED';

export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_REQUEST_PENDING = 'UPDATE_REQUEST_PENDING';
export const UPDATE_REQUEST_FULFILLED = 'UPDATE_REQUEST_FULFILLED';
export const UPDATE_REQUEST_REJECTED = 'UPDATE_REQUEST_REJECTED';

export const UPDATE_REQUEST_MANUALLY = 'UPDATE_REQUEST_MANUALLY';
