export const AUTHENTICATE = 'AUTHENTICATE';
export const CLEAR_AUTHENTICATE = 'CLEAR_AUTHENTICATE';

export const AUTHENTICATE_PENDING = 'AUTHENTICATE_PENDING';
export const AUTHENTICATE_FULFILLED = 'AUTHENTICATE_FULFILLED';
export const AUTHENTICATE_REJECTED = 'AUTHENTICATE_REJECTED';
