export const CLEAR_REQUEST_LIST = 'CLEAR_REQUEST_LIST';

export const GET_REQUEST_LIST = 'GET_REQUEST_LIST';
export const GET_REQUEST_LIST_PENDING = 'GET_REQUEST_LIST_PENDING';
export const GET_REQUEST_LIST_FULFILLED = 'GET_REQUEST_LIST_FULFILLED';
export const GET_REQUEST_LIST_REJECTED = 'GET_REQUEST_LIST_REJECTED';
